### ISSUE TITLE
Error when Downloading using Download Manager

### ISSUE THREAD

**Issue by ghost** [webtor-io/download-progress#1]
When using Webtor to Download from Firefox using Free Download Manager, FDM gets `HTTP Error 403` and the Download Starts in the Browser instead. 

While as if the Download is started from Webtor in any Chromium based Browser. It works Seamlessly with no HTTP Error.

I think that this should be Fixed and this Problem is recently after Firefox Version 91 or above.

![Snap 18](https://user-images.githubusercontent.com/87981739/135273001-46ca6d35-a1a1-4b8b-af87-387a96f64a4f.png)

Side Note : The RSS Feed for your Blog is Broken and Please fix it.

**Comment by vintikzzz** [comment]
@Loki-L1130 Hi! The problem is fixed. Can you confirm?

**Comment by ghost** [comment]
@vintikzzz, The Issue is Fixed and Working as it is was in Firefox.

**Comment by ghost** [comment]
A note regarding this issue. I do tested this out with a VPN. It works finely with WireGuard and refuses if the connection is using OpenVPN UDP or TCP Protocol. I just tested this with a VPN, You can Try out ProtonVPN and Windscribe for free to check this out. Both suffers the same.

Reopening this as if you might consider fixing this

**Comment by ghost** [comment]
I am closing this issue as HTTP Error 403 in download is fixed in OpenVPN Protocol, both UDP and TCP.
