### ISSUE TITLE
Resuming Downloads

### ISSUE THREAD

**Issue by ghost** [webtor-io/download-progress#2]
When Downloading from Webtor, If Internet connection is disrupted and is back after a Couple of Minutes. The Download in Free Download Manager shows Resource Changed & makes the Download useless and if downloaded via Browser it says Download failed after back online.

I think that as Specific Download URL is assigned to Specific IP after reconnection if IP is changed this is caused. I think that you can better have a Timout of 5 to 10 Minutes for this case to prevent this Happen.

Sometime, Even Paused and Resuming after 5 Minutes makes this. 

To get back the Track of Download, If gone to the Same and Use the Different Download Link and trying to resume also doesn't work.

Is there a way to fix this ?

**Comment by vintikzzz** [comment]
@Loki-L1130 Hi! Every resource url (and download also) is bound to IP. If IP changes you have to use new url. I don't know why some browsers and download managers unable to resume download, I tried to find some information about it, but had no luck. As a workaround you can try [Wget](https://www.gnu.org/software/wget/), Webtor also has UI to generate command line to download with it. If you have some more information about cause of resuming failures, please share!

**Comment by ghost** [comment]
As a matter of Fact, I tried downloading from Webtor and after successfule Catching and it downloaded for 3% and I Paused it in FDM and Restarted my Router to get a new IP and Clicking on Resume showed `Resource Changed` after that a Popup came in FDM saying that "Resource Changed, Please Update Download URL" with the Link to Download Page.

If I do Copy and Paste the Download Link in the Existing One. It is unable to resume the Download but can be started as Fresh from the start.

@vintikzzz Regarding, Wget is CLI and which is not suitable for me. Free Download Manager is available on all Platforms, You can try it for Yourself, Consider Xtreme Download Manager, Motrix and Internet Download Manager (30-Day Trial) to your list for Testing. And You can use FreeVPNs such as ProtonVPN or Windscribe to test for yourself (I am saying VPNs in the case if you find it harder to change IP by Turning on and off your Router).

Is there anyother way, I can help on this ?

**Comment by ghost** [comment]
I will try Wget and tell you if this happens there too. I think I can make it.

Edit : I do tried downloading using Wget but what I get is these : 

`Resolving ... failed : No such host is known`
`wget: unable to resolve host address ...... `

..... is given part of the URL in every Command Line.

```
'download' is not recognized as an internal or external command,
operable program or batch file.
'download-id' is not recognized as an internal or external command,
operable program or batch file.
'token' is not recognized as an internal or external command,
operable program or batch file.
'api-key' is not recognized as an internal or external command,
operable program or batch file. 
```

**Comment by vintikzzz** [comment]
@Loki-L1130 Have you just copied command as is? Can you share it? It should looks like this
```
wget -c -O 'Sintel.mp4' -t 20 --retry-connrefused --retry-on-http-error=500,502 'https://abra--a2376523.api.ftor.cc/08ada5a7a6183aae1e09d831df6748d566095a10/Sintel%2FSintel.mp4~tc/Sintel.mp4?user-id=47a2fa1d7ac8983e73383169de799302&download=true&download-id=695c175f902a6c4671364a65fc337f1a&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudCI6Ik1vemlsbGEvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS85NC4wLjQ2MDYuNjEgU2FmYXJpLzUzNy4zNiIsInJlbW90ZUFkZHJlc3MiOiI0Ni4xNjAuMjU1LjE5NyIsImRvbWFpbiI6IndlYnRvci5pbyIsImV4cCI6MTYzMzk1MzkyNiwic2Vzc2lvbklEIjoiYVg1c0V4Vmw3cEFGeXA2NmNaNUFmSUZtbjdSOFd2eHIiLCJhZHMiOnRydWUsInJhdGUiOiIxME0iLCJyb2xlIjoibm9ib2R5In0.PLaThwQgF7k5SR1BAQfA2ncBKEKS582XeFNMfMO78n0&api-key=8acbcf1e-732c-4574-a3bf-27e6a85b86f1'
```

**Comment by ghost** [comment]
I think I do, See below : 


```
wget -c -O 'elementaryos-6.0-stable.20210831.iso' -t 20 --retry-connrefused --retry-on-http-error=500,502 'https://abra--8ac92139.api.ftor.cc/7b4bce53195f7db8c0ba9b9db04b20228b84b60b/elementaryos-6.0-stable.20210831.iso?user-id=832310b47003ac05bf271163c0a2e08c&download=true&download-id=6193a40f8c21e9229886b333aeca5f0f&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IHJ2OjkxLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvOTEuMCIsInJlbW90ZUFkZHJlc3MiOiI0Ni4xNjYuMTgyLjcyIiwiZG9tYWluIjoid2VidG9yLmlvIiwiZXhwIjoxNjM0MTA5MjYyLCJzZXNzaW9uSUQiOiJTVkJSdENpc0JmNjNYVW9VVUhmTzdvV3d4eFN2Mm1iSCIsImFkcyI6dHJ1ZSwicmF0ZSI6IjEwTSIsInJvbGUiOiJub2JvZHkifQ.c9_l7lD-eI3rQutg24qLOcPaFx3aRvQAmv0DGTNrAaA&api-key=8acbcf1e-732c-4574-a3bf-27e6a85b86f1'
```

**Comment by ghost** [comment]
This is the Input and Output I got in Elevated Command Prompt.

```
C:\WINDOWS\system32>wget -c -O 'elementaryos-6.0-stable.20210831.iso' -t 20 --retry-connrefused --retry-on-http-error=500,502 'https://abra--8ac92139.api.ftor.cc/7b4bce53195f7db8c0ba9b9db04b20228b84b60b/elementaryos-6.0-stable.20210831.iso?user-id=832310b47003ac05bf271163c0a2e08c&download=true&download-id=6193a40f8c21e9229886b333aeca5f0f&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IHJ2OjkxLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvOTEuMCIsInJlbW90ZUFkZHJlc3MiOiI0Ni4xNjYuMTgyLjcyIiwiZG9tYWluIjoid2VidG9yLmlvIiwiZXhwIjoxNjM0MTA5MjYyLCJzZXNzaW9uSUQiOiJTVkJSdENpc0JmNjNYVW9VVUhmTzdvV3d4eFN2Mm1iSCIsImFkcyI6dHJ1ZSwicmF0ZSI6IjEwTSIsInJvbGUiOiJub2JvZHkifQ.c9_l7lD-eI3rQutg24qLOcPaFx3aRvQAmv0DGTNrAaA&api-key=8acbcf1e-732c-4574-a3bf-27e6a85b86f1'
'https://abra--8ac92139.api.ftor.cc/7b4bce53195f7db8c0ba9b9db04b20228b84b60b/elementaryos-6.0-stable.20210831.iso?user-id=832310b47003ac05bf271163c0a2e08c: Scheme missing.
'download' is not recognized as an internal or external command,
operable program or batch file.
'download-id' is not recognized as an internal or external command,
operable program or batch file.
'token' is not recognized as an internal or external command,
operable program or batch file.
'api-key' is not recognized as an internal or external command,
operable program or batch file.
```

I downloaded Wget from here : https://eternallybored.org/misc/wget/

Used the Guide from here : https://builtvisible.com/download-your-website-with-wget/

**Comment by ghost** [comment]
Do you have anything on this ?

Free Download Manager says resource changed if it is paused and then resumed after 2 Minutes. I tried this in a VPN, If I changed networks while the VPN is on it is queued and then "Resource Changed" . The same thing on Issue #1 - Latest comment applies here.

Unable to resume the download where it left. I think that this should be fixed as it is crucial for some people as I use Webtor only sometimes. 

Just helping you

**Comment by vintikzzz** [comment]
Hi @Loki-L1130 
I found few issues with resuming of downloads. I finally fixed them. Can you confirm?

**Comment by ghost** [comment]
@vintikzzz It seems like you fixed it. I turned on my VPN for the Testing.For the First case, Fetched a URL for Download. Started download Upto 2% and with VPN in on. I changed my networks. It was queued until successfully changed. Then resumed.

In the 2nd case, This is also worked I paused the Download for 5 Minutes and it resumed the download successfully.. It doesn't give an `HTTP Error 403`.

So, Again for the 3rd case. I changed the IP by connecting to a different server it got an `HTTP Error 403`. I know that each download URL is bound to an IP. So, the server refused. I got it.

But is there a way to resume after an IP Change ?

Is there any Timeout for the download after an URL is created ?

**Comment by vintikzzz** [comment]
@Loki-L1130 I am thinking about to allow several IP-changes during the session. I am sure this could solve this problem.

**Comment by ghost** [comment]
> I am thinking about to allow several IP-changes during the session. I am sure this could solve this problem.
Oh, Great to know about it. 

But you haven't answered this :
> Is there any Timeout for the download after an URL is created ?

**Comment by vintikzzz** [comment]
> Is there any Timeout for the download after an URL is created?

Every link has an expiration period that equals one week. So you can perform download during the first week after its creation.

**Comment by ghost** [comment]
Great to know. I think that it is actually a great time period but resuming after an IP change should make this time limit more efficient.

Looking for your fix regarding it. I will close this issue now. 

And either you or I should mention here that it could be able to resume after an IP Change. After it is Posssible to do so.

**Comment by vintikzzz** [comment]
@Loki-L1130 now it is possible to make 10 changes of combination UserAgent + IP without any restrictions. Can you confirm that it works for you?

**Comment by ghost** [comment]
@vintikzzz I didn't try changing user Agent in my Browser using an Add-On but Changing IP about 10-15 times did make it by resuming. After that `HTTP Error 403`. So, I think you did it.

Perfect thing. Should I need to check for User Agent too ? 

If so, tell me about your preference to change User Agent Strings.

Note : After getting an `HTTP Error 403`, I need to always start from the first but now I can resume the download by updating the download link. Which was not possible before.

**Comment by vintikzzz** [comment]
> Perfect thing. Should I need to check for User Agent too ?

It's not so important. The good thing is that service works for you now.
