### ISSUE TITLE
Error in Downloading 

### ISSUE THREAD

**Issue by ghost** [webtor-io/download-progress#3]
After v1.12.0 The Torrenting File stucks at 1% of the File Size seeding in the Download Popup even if the Torrent has more than 3000 + Seeders.

It has also do not download and Stucks in my Download Manager and it keeps failing.

**Comment by vintikzzz** [comment]
Hi! Can you share your torrent or magnet uri? I need to check it. I have tried to download few torrents after release and there were no errors.

**Comment by ghost** [comment]
It seems to be fixed now after clearing Cache and Cookies for Webtor.io. I think that the transition from v 1.11.0 to 1.12.0 during the download caused the download to have some errors.
