### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by ghost** [webtor-io/download-progress#4]
when Download from Webtor, In the Download URL at the end there is a part &api-key= with random characters which is always specific for my Device. Is it derived by Fingerprinting my Device. Why was it so ?

Same for any Download and even on Different Devices. Is it assigned based on IP address ?

**Comment by vintikzzz** [comment]
Hi @Loki-L1130 
User's IP and UA (User-Agent) are part of `token` GET-parameter. Also you can use generated url from another device with different UA and IP, but this change is possible only for limited number of times. This restrictions were introduced to avoid link hijacking (when somebody just grabs url from the original site and uses it on another one). Also webtor links are time-limited for the same purpose. Webtor uses JWT-based tokens so you can always decode them online at [jwt.io](https://jwt.io/)

**Comment by ghost** [comment]
But the API Key is still the same even when I change the Browser and IP. How could I jwt.io and what is it the use of it. Could you explain it ?

**Comment by vintikzzz** [comment]
API key stays the same, it just indicates for Webtor backend API that request was made from Webtor frontend (webtor.io site). You can use jwt.io to decode `token` GET-parameter from download url. You can also read more about JWT [here](https://en.wikipedia.org/wiki/JSON_Web_Token).

**Comment by ghost** [comment]
I did understand decoded the TOKEN parameter but what is the 'exp' and 'role' in Payload Data.

**Comment by ghost** [comment]
This is off-topic. Are you active in the subreddit community ?

**Comment by vintikzzz** [comment]
Quite active, you can always ask questions there https://www.reddit.com/r/webtor/

**Comment by ghost** [comment]
> Quite active, you can always ask questions there https://www.reddit.com/r/webtor/

Because you haven't replied to post that are about a week/Month old which are related to support.

**Comment by ghost** [comment]
> I did understand decoded the TOKEN parameter but what is the 'exp' and 'role' in Payload Data.

Can you explain this ?

**Comment by vintikzzz** [comment]
`role` corresponds user's to Patreon tier, API makes traffic throttling according to it's value.
`exp` - just short of `expiration`, time in future when token is going to expire. It is very common field for JWT tokens.

**Comment by ghost** [comment]
> `role` corresponds user's to Patreon tier, API makes traffic throttling according to it's value. `exp` - just short of `expiration`, time in future when token is going to expire. It is very common field for JWT tokens.

Okay but 'exp' is with long string numbers in my Token.

**Comment by vintikzzz** [comment]
It should look like this
```
"exp": 1644852433,
```
It is Unix timestamp, number of seconds from [1970-01-01 00:00:00Z](https://en.wikipedia.org/wiki/Unix_time)

**Comment by ghost** [comment]
Oh, Okay. Thanks for Helping out.
